//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ngClassifiedsAPI
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.Categories = new HashSet<Category>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }

        [RegularExpression("^[0-9]*$", ErrorMessage = "Price must contain only numbers")]
        public double Price { get; set; }
        public System.DateTime Posted { get; set; }
        public int UserId { get; set; }
        public string Image { get; set; }
        public int Views { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Categories { get; set; }
    }
}
